// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/classes/[name].ts";
import * as $1 from "./routes/api/classes/index.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/archmage.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/api/classes/[name].ts": $0,
    "./routes/api/classes/index.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/archmage.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
